/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SeedErrors from "../../../index";
import express from "express";
import * as serializers from "../../../../serialization/index";
import * as errors from "../../../../errors/index";

export interface SimpleServiceMethods {
    fooWithoutEndpointError(
        req: express.Request<never, SeedErrors.FooResponse, SeedErrors.FooRequest, never>,
        res: {
            send: (responseBody: SeedErrors.FooResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
            locals: any;
        },
        next: express.NextFunction,
    ): void | Promise<void>;
    foo(
        req: express.Request<never, SeedErrors.FooResponse, SeedErrors.FooRequest, never>,
        res: {
            send: (responseBody: SeedErrors.FooResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
            locals: any;
        },
        next: express.NextFunction,
    ): void | Promise<void>;
    fooWithExamples(
        req: express.Request<never, SeedErrors.FooResponse, SeedErrors.FooRequest, never>,
        res: {
            send: (responseBody: SeedErrors.FooResponse) => Promise<void>;
            cookie: (cookie: string, value: string, options?: express.CookieOptions) => void;
            locals: any;
        },
        next: express.NextFunction,
    ): void | Promise<void>;
}

export class SimpleService {
    private router;

    constructor(
        private readonly methods: SimpleServiceMethods,
        middleware: express.RequestHandler[] = [],
    ) {
        this.router = express.Router({ mergeParams: true }).use(
            express.json({
                strict: false,
            }),
            ...middleware,
        );
    }

    public addMiddleware(handler: express.RequestHandler): this {
        this.router.use(handler);
        return this;
    }

    public toRouter(): express.Router {
        this.router.post("/foo1", async (req, res, next) => {
            const request = serializers.FooRequest.parse(req.body);
            if (request.ok) {
                req.body = request.value;
                try {
                    await this.methods.fooWithoutEndpointError(
                        req as any,
                        {
                            send: async (responseBody) => {
                                res.json(
                                    serializers.FooResponse.jsonOrThrow(responseBody, {
                                        unrecognizedObjectKeys: "strip",
                                    }),
                                );
                            },
                            cookie: res.cookie.bind(res),
                            locals: res.locals,
                        },
                        next,
                    );
                    if (!res.writableEnded) {
                        next();
                    }
                } catch (error) {
                    if (error instanceof errors.SeedErrorsError) {
                        switch (error.errorName) {
                            case "NotFoundError":
                            case "BadRequestError":
                            case "InternalServerError":
                                break;
                            default:
                                console.warn(
                                    `Endpoint 'fooWithoutEndpointError' unexpectedly threw ${error.constructor.name}.` +
                                        ` If this was intentional, please add ${error.constructor.name} to` +
                                        " the endpoint's errors list in your Fern Definition.",
                                );
                        }
                        await error.send(res);
                    } else {
                        res.status(500).json("Internal Server Error");
                    }
                    next(error);
                }
            } else {
                res.status(422).json({
                    errors: request.errors.map(
                        (error) => ["request", ...error.path].join(" -> ") + ": " + error.message,
                    ),
                });
                next(request.errors);
            }
        });
        this.router.post("/foo2", async (req, res, next) => {
            const request = serializers.FooRequest.parse(req.body);
            if (request.ok) {
                req.body = request.value;
                try {
                    await this.methods.foo(
                        req as any,
                        {
                            send: async (responseBody) => {
                                res.json(
                                    serializers.FooResponse.jsonOrThrow(responseBody, {
                                        unrecognizedObjectKeys: "strip",
                                    }),
                                );
                            },
                            cookie: res.cookie.bind(res),
                            locals: res.locals,
                        },
                        next,
                    );
                    if (!res.writableEnded) {
                        next();
                    }
                } catch (error) {
                    if (error instanceof errors.SeedErrorsError) {
                        switch (error.errorName) {
                            case "FooTooMuch":
                            case "FooTooLittle":
                            case "NotFoundError":
                            case "BadRequestError":
                            case "InternalServerError":
                                break;
                            default:
                                console.warn(
                                    `Endpoint 'foo' unexpectedly threw ${error.constructor.name}.` +
                                        ` If this was intentional, please add ${error.constructor.name} to` +
                                        " the endpoint's errors list in your Fern Definition.",
                                );
                        }
                        await error.send(res);
                    } else {
                        res.status(500).json("Internal Server Error");
                    }
                    next(error);
                }
            } else {
                res.status(422).json({
                    errors: request.errors.map(
                        (error) => ["request", ...error.path].join(" -> ") + ": " + error.message,
                    ),
                });
                next(request.errors);
            }
        });
        this.router.post("/foo3", async (req, res, next) => {
            const request = serializers.FooRequest.parse(req.body);
            if (request.ok) {
                req.body = request.value;
                try {
                    await this.methods.fooWithExamples(
                        req as any,
                        {
                            send: async (responseBody) => {
                                res.json(
                                    serializers.FooResponse.jsonOrThrow(responseBody, {
                                        unrecognizedObjectKeys: "strip",
                                    }),
                                );
                            },
                            cookie: res.cookie.bind(res),
                            locals: res.locals,
                        },
                        next,
                    );
                    if (!res.writableEnded) {
                        next();
                    }
                } catch (error) {
                    if (error instanceof errors.SeedErrorsError) {
                        switch (error.errorName) {
                            case "FooTooMuch":
                            case "FooTooLittle":
                            case "NotFoundError":
                            case "BadRequestError":
                            case "InternalServerError":
                                break;
                            default:
                                console.warn(
                                    `Endpoint 'fooWithExamples' unexpectedly threw ${error.constructor.name}.` +
                                        ` If this was intentional, please add ${error.constructor.name} to` +
                                        " the endpoint's errors list in your Fern Definition.",
                                );
                        }
                        await error.send(res);
                    } else {
                        res.status(500).json("Internal Server Error");
                    }
                    next(error);
                }
            } else {
                res.status(422).json({
                    errors: request.errors.map(
                        (error) => ["request", ...error.path].join(" -> ") + ": " + error.message,
                    ),
                });
                next(request.errors);
            }
        });
        return this.router;
    }
}
